// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_screen1
void ui_screen1_screen_init(void);
extern lv_obj_t * ui_screen1;
extern lv_obj_t * ui_soccontainer;
extern lv_obj_t * ui_socbar;
extern lv_obj_t * ui_soclabel;
extern lv_obj_t * ui_batteryvoltagelabel;
extern lv_obj_t * ui_homebar4;
extern lv_obj_t * ui_bar1;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui_homebar2;
extern lv_obj_t * ui_bar3;
extern lv_obj_t * ui_label4;
extern lv_obj_t * ui_container3;
extern lv_obj_t * ui_button2;
extern lv_obj_t * ui_label3;
extern lv_obj_t * ui_container1;
extern lv_obj_t * ui_button1;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
