// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_screen1_screen_init(void)
{
    ui_screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soccontainer = lv_obj_create(ui_screen1);
    lv_obj_remove_style_all(ui_soccontainer);
    lv_obj_set_width(ui_soccontainer, lv_pct(90));
    lv_obj_set_height(ui_soccontainer, lv_pct(20));
    lv_obj_set_x(ui_soccontainer, 0);
    lv_obj_set_y(ui_soccontainer, lv_pct(-38));
    lv_obj_set_align(ui_soccontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_soccontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_socbar = lv_bar_create(ui_soccontainer);
    lv_bar_set_value(ui_socbar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_socbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_socbar, lv_pct(100));
    lv_obj_set_height(ui_socbar, lv_pct(100));
    lv_obj_set_align(ui_socbar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_socbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_socbar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_socbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_socbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_socbar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_socbar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_socbar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_socbar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_socbar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_socbar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_socbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_socbar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_socbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_soclabel = lv_label_create(ui_soccontainer);
    lv_obj_set_width(ui_soclabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soclabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soclabel, lv_pct(40));
    lv_obj_set_y(ui_soclabel, lv_pct(0));
    lv_obj_set_align(ui_soclabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soclabel, "50%");
    lv_obj_set_style_text_color(ui_soclabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soclabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soclabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryvoltagelabel = lv_label_create(ui_soccontainer);
    lv_obj_set_width(ui_batteryvoltagelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryvoltagelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batteryvoltagelabel, lv_pct(-40));
    lv_obj_set_y(ui_batteryvoltagelabel, lv_pct(0));
    lv_obj_set_align(ui_batteryvoltagelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batteryvoltagelabel, "500V");
    lv_obj_set_style_text_color(ui_batteryvoltagelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batteryvoltagelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batteryvoltagelabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebar4 = lv_obj_create(ui_screen1);
    lv_obj_remove_style_all(ui_homebar4);
    lv_obj_set_width(ui_homebar4, lv_pct(20));
    lv_obj_set_height(ui_homebar4, lv_pct(66));
    lv_obj_set_x(ui_homebar4, lv_pct(35));
    lv_obj_set_y(ui_homebar4, lv_pct(12));
    lv_obj_set_align(ui_homebar4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_homebar4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bar1 = lv_bar_create(ui_homebar4);
    lv_bar_set_value(ui_bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar1, lv_pct(100));
    lv_obj_set_height(ui_bar1, lv_pct(80));
    lv_obj_set_x(ui_bar1, lv_pct(0));
    lv_obj_set_y(ui_bar1, lv_pct(10));
    lv_obj_set_align(ui_bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_bar1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar1, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_label1 = lv_label_create(ui_homebar4);
    lv_obj_set_width(ui_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label1, lv_pct(0));
    lv_obj_set_y(ui_label1, lv_pct(-42));
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1, "20°C");
    lv_obj_set_style_text_color(ui_label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebar2 = lv_obj_create(ui_screen1);
    lv_obj_remove_style_all(ui_homebar2);
    lv_obj_set_width(ui_homebar2, lv_pct(20));
    lv_obj_set_height(ui_homebar2, lv_pct(66));
    lv_obj_set_x(ui_homebar2, lv_pct(-35));
    lv_obj_set_y(ui_homebar2, lv_pct(12));
    lv_obj_set_align(ui_homebar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_homebar2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bar3 = lv_bar_create(ui_homebar2);
    lv_bar_set_value(ui_bar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar3, lv_pct(100));
    lv_obj_set_height(ui_bar3, lv_pct(80));
    lv_obj_set_x(ui_bar3, lv_pct(0));
    lv_obj_set_y(ui_bar3, lv_pct(10));
    lv_obj_set_align(ui_bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_bar3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar3, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bar3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bar3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bar3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bar3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bar3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_bar3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar3, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_label4 = lv_label_create(ui_homebar2);
    lv_obj_set_width(ui_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label4, lv_pct(0));
    lv_obj_set_y(ui_label4, lv_pct(-42));
    lv_obj_set_align(ui_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label4, "20°C");
    lv_obj_set_style_text_color(ui_label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container3 = lv_obj_create(ui_screen1);
    lv_obj_remove_style_all(ui_container3);
    lv_obj_set_width(ui_container3, lv_pct(40));
    lv_obj_set_height(ui_container3, lv_pct(18));
    lv_obj_set_align(ui_container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button2 = lv_btn_create(ui_container3);
    lv_obj_set_width(ui_button2, lv_pct(104));
    lv_obj_set_height(ui_button2, lv_pct(104));
    lv_obj_set_align(ui_button2, LV_ALIGN_CENTER);

    ui_label3 = lv_label_create(ui_button2);
    lv_obj_set_width(ui_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label3, "60kW");
    lv_obj_set_style_text_font(ui_label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container1 = lv_obj_create(ui_screen1);
    lv_obj_remove_style_all(ui_container1);
    lv_obj_set_width(ui_container1, lv_pct(40));
    lv_obj_set_height(ui_container1, lv_pct(18));
    lv_obj_set_x(ui_container1, lv_pct(0));
    lv_obj_set_y(ui_container1, lv_pct(30));
    lv_obj_set_align(ui_container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button1 = lv_btn_create(ui_container1);
    lv_obj_set_width(ui_button1, lv_pct(104));
    lv_obj_set_height(ui_button1, lv_pct(104));
    lv_obj_set_align(ui_button1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_button1, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2 = lv_label_create(ui_button1);
    lv_obj_set_width(ui_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2, "CLOSED");
    lv_obj_set_style_text_color(ui_label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}
