// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_voltageL = ui_voltageL_create(ui_Screen1);
    lv_obj_set_x(ui_voltageL, -8);
    lv_obj_set_y(ui_voltageL, -97);

    ui_batteryPercentL = ui_voltageL_create(ui_Screen1);
    lv_obj_set_x(ui_batteryPercentL, -23);
    lv_obj_set_y(ui_batteryPercentL, -27);
    lv_label_set_text(ui_batteryPercentL, "0%");

    ui_speedL = ui_voltageL_create(ui_Screen1);
    lv_obj_set_x(ui_speedL, -10);
    lv_obj_set_y(ui_speedL, 43);
    lv_label_set_text(ui_speedL, "0 km/h");

}
