// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT homebar

lv_obj_t * ui_homebar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_homebar;
    cui_homebar = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_homebar);
    lv_obj_set_width(cui_homebar, lv_pct(15));
    lv_obj_set_height(cui_homebar, lv_pct(66));
    lv_obj_set_align(cui_homebar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_homebar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_bar2;
    cui_bar2 = lv_bar_create(cui_homebar);
    lv_bar_set_value(cui_bar2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_bar2, lv_pct(100));
    lv_obj_set_height(cui_bar2, lv_pct(80));
    lv_obj_set_x(cui_bar2, lv_pct(0));
    lv_obj_set_y(cui_bar2, lv_pct(10));
    lv_obj_set_align(cui_bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_bar2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_bar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_bar2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_bar2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_bar2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_bar2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_bar2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_bar2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_bar2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_bar2, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t * cui_label2;
    cui_label2 = lv_label_create(cui_homebar);
    lv_obj_set_width(cui_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_label2, lv_pct(0));
    lv_obj_set_y(cui_label2, lv_pct(-42));
    lv_obj_set_align(cui_label2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label2, "20°C");
    lv_obj_set_style_text_color(cui_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HOMEBAR_NUM);
    children[UI_COMP_HOMEBAR_HOMEBAR] = cui_homebar;
    children[UI_COMP_HOMEBAR_BAR2] = cui_bar2;
    children[UI_COMP_HOMEBAR_LABEL2] = cui_label2;
    lv_obj_add_event_cb(cui_homebar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_homebar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_homebar_create_hook(cui_homebar);
    return cui_homebar;
}

