// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_VOLTAGEL_H
#define _UI_COMP_VOLTAGEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT voltageL
#define UI_COMP_VOLTAGEL_VOLTAGEL 0
#define _UI_COMP_VOLTAGEL_NUM 1
lv_obj_t * ui_voltageL_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
