// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_HOMEBAR_H
#define _UI_COMP_HOMEBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT homebar
#define UI_COMP_HOMEBAR_HOMEBAR 0
#define UI_COMP_HOMEBAR_BAR2 1
#define UI_COMP_HOMEBAR_LABEL2 2
#define _UI_COMP_HOMEBAR_NUM 3
lv_obj_t * ui_homebar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
